version: 2
builds:
  - main: ./cmd/yomiyasu-go
    binary: yomiyasu-go
    env:
      - CGO_ENABLED=0
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/sudame/yomiyasu-go/internal/cli.Version={{.Version}}
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md
checksum:
  name_template: checksums.txt
